//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarName
    {
        public CarName()
        {
            this.CarType = new HashSet<CarType>();
        }
    
        public int id { get; set; }
        public string carname1 { get; set; }
    
        public virtual ICollection<CarType> CarType { get; set; }
    }
}
