//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsProducers
    {
        public CarsProducers()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public int cartypeid { get; set; }
        public int producerid { get; set; }
    
        public virtual CarType CarType { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
