//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        public CarType()
        {
            this.CarsProducers = new HashSet<CarsProducers>();
        }
    
        public int id { get; set; }
        public string cartype1 { get; set; }
        public int carnameID { get; set; }
    
        public virtual CarName CarName { get; set; }
        public virtual ICollection<CarsProducers> CarsProducers { get; set; }
    }
}
