//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id { get; set; }
        public int customerId { get; set; }
        public int producCartId { get; set; }
        public decimal sum_price { get; set; }
        public int cartitems { get; set; }
        public string items_list { get; set; }
        public System.DateTime shoppingdate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductCart ProductCart { get; set; }
    }
}
