//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Producer = new HashSet<Producer>();
        }
    
        public int id { get; set; }
        public string categoryname { get; set; }
    
        public virtual ICollection<Producer> Producer { get; set; }
    }
}
