//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Cart = new HashSet<Cart>();
        }
    
        public int id { get; set; }

        [StringLength(100,MinimumLength=5, ErrorMessage = "Max 100 és minimum 5 karakterbõl álló név megadása kötelezõ!")]
        public string name { get; set; }
        
        [DataType(DataType.EmailAddress,ErrorMessage="Helytelen e-mail cím")]
        [EmailAddress]
        public string email { get; set; }
        
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateofbirth { get; set; }

        [StringLength(100, MinimumLength = 5, ErrorMessage = "Teljes lakcím hossza max 100 és min 5 karakter!")]
        public string address { get; set; }
        
        [Required]
        [StringLength(50,MinimumLength=5, ErrorMessage = "Felhasználónév hossza max 50 és min 5 karakter!")]
        public string username { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Jelszó hossza max 100 és min 5 karakter!")]
        public string password { get; set; }
        
        public Nullable<bool> paid { get; set; }
        public Nullable<decimal> price { get; set; }
   
        public virtual ICollection<Cart> Cart { get; set; }
    }
}
