//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCart
    {
        public ProductCart()
        {
            this.Cart = new HashSet<Cart>();
        }
    
        public int id { get; set; }
        public int productid { get; set; }
    
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
