//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proba.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductCart = new HashSet<ProductCart>();
        }
    
        public int id { get; set; }
        public int carsproducersid { get; set; }
        public string size { get; set; }
        public bool instorage { get; set; }
        public decimal price { get; set; }
    
        public virtual CarsProducers CarsProducers { get; set; }
        public virtual ICollection<ProductCart> ProductCart { get; set; }
    }
}
